### ISSUE TITLE
Check email issue

### ISSUE THREAD

**Issue by peternagelsa** [fengoffice/fengoffice#16]
Setting up a pop3 email address works as expected, but when emails are checked it generates a blank screen:

<img width="798" alt="check email" src="https://user-images.githubusercontent.com/47089603/53939222-1cef0800-40bb-11e9-8a59-98b623a8733b.PNG">

Refreshing the page, generates the default:

<img width="816" alt="email" src="https://user-images.githubusercontent.com/47089603/53939259-36904f80-40bb-11e9-9c60-28e62f144d86.PNG">

Feng Office Version 3.7.1.1
PHP 7.2 

This has become an issue since we moved over to PHP 7. I need to state that the checking email and pulling in of emails works on PHP 7.0. 

Thanks
Peter

**Comment by peternagelsa** [comment]
I have updated my Feng Office install to the latest version 3.7.2.16 running PHP 7.2. Unfortunately, the issue I am experiencing with getting a blank page when checking email remains unresolved. This issue also occurs when I do a search.

**Comment by nagraskal** [comment]
I have the same issues. I found two issues in the log, one concerning using tls for the account, which gave me a 
`#1 ERROR: Error: stream_socket_client(): Failed to enable crypto in 'library/PEAR/Net/Socket.php' on line 220 (error code: 2)`
I'm still investigating this one, for now I disabled tls for testing.

Second issue was 
`/PEAR/Net/Socket.php FATAL: ArgumentCountError: Too few arguments to function Net_Socket::setTimeout(), 0 passed` 
Here I changed line 251 in 
library/PEAR/Net/Socket.php
to
`this->setTimeout('30','0');`
then it works.

this is just a very dirty hack, I'm still looking into this to find a proper solution.

regards,
Roger

**Comment by peternagelsa** [comment]
Hi Nagraskal

Did you find a solution to the email problem?

Thanks
Peter

**Comment by peternagelsa** [comment]
Hi Roger

I get the following error when sending email. The email does get sent, but it returns a blank page:

FATAL: ArgumentCountError: Too few arguments to function Hook::fire(), 2 passed in  plugins/mail/application/controllers/MailController.class.php on line 752 and exactly 3 expected 

Any idea how one could resolve this?
Peter
